### ISSUE TITLE
Deprecations on Homebrew Tap

### ISSUE THREAD

**Issue by acbarbosa** [bltavares/kickstart#9]
When I added the tap to brew, I've got the following warning messages"

```
$ brew tap bltavares/tap
==> Tapping bltavares/tap
Cloning into '/usr/local/Homebrew/Library/Taps/bltavares/homebrew-tap'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/bltavares/homebrew-tap/baseline.rb:4:in `<class:Baseline>'
Please report this to the bltavares/tap tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/bltavares/homebrew-tap/baseline.rb:4:in `<class:Baseline>'
Please report this to the bltavares/tap tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/bltavares/homebrew-tap/baseline.rb:4:in `<class:Baseline>'
Please report this to the bltavares/tap tap!

Tapped 3 formulae (32 files, 22.6K)
```

**Comment by bltavares** [comment]
Thanks for the report @acbarbosa. I've fixed the tap to not use the deprecated hashing anymore.
